[package]
name = "digitize"
version = "0.1.0"
edition = "2021"
authors = ["beetle"]
license = "MIT"
description = "Traits for accessing digits of primitive integers & floats"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
